import type { Prediction, Profile, LeaderboardEntry, CategoryInsight, InsightTrend } from '@/types'

// ── ZAWIOS Avatar System — 12 canonical personas ──────────────────────────
// Named after the official Avatar Guideline Board
// Photos: /avatars/adebayo.jpg etc. (add real images when available)

export const mockProfiles: Profile[] = [
  {
    id: '1',
    user_id: 'u1',
    username: 'adebayo_a',
    full_name: 'A. Adebayo',
    avatar_url: '/avatars/adebayo.jpg',
    bio: 'Macro strategist & data analyst. 12 years tracking global markets.',
    location: 'Lagos, Nigeria',
    is_premium: true,
    plan: 'business',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-03-01T10:00:00Z',
  },
  {
    id: '2',
    user_id: 'u2',
    username: 'mchen',
    full_name: 'M. Chen',
    avatar_url: '/avatars/chen.jpg',
    bio: 'Tech journalist & future-spotter. 78% accuracy on tech signals.',
    location: 'Singapore',
    is_premium: true,
    plan: 'creator',
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-03-01T10:00:00Z',
  },
  {
    id: '3',
    user_id: 'u3',
    username: 'j_schmidt',
    full_name: 'J. Schmidt',
    avatar_url: '/avatars/schmidt.jpg',
    bio: 'Senior economist. Former IMF. Tracking macro trends since 2001.',
    location: 'Berlin, Germany',
    is_premium: true,
    plan: 'business',
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-03-01T10:00:00Z',
  },
  {
    id: '4',
    user_id: 'u4',
    username: 'sgupta',
    full_name: 'S. Gupta',
    avatar_url: '/avatars/gupta.jpg',
    bio: 'Crypto researcher & fintech analyst. Building Web3 signals.',
    location: 'Mumbai, India',
    is_premium: false,
    plan: 'premium',
    created_at: '2024-02-10T10:00:00Z',
    updated_at: '2024-03-01T10:00:00Z',
  },
  {
    id: '5',
    user_id: 'u5',
    username: 'h_alfassi',
    full_name: 'H. Al-Fassi',
    avatar_url: '/avatars/alfassi.jpg',
    bio: 'Cultural researcher & society analyst. Global perspectives.',
    location: 'Casablanca, Morocco',
    is_premium: false,
    plan: 'free',
    created_at: '2024-02-15T10:00:00Z',
    updated_at: '2024-03-01T10:00:00Z',
  },
  {
    id: '6',
    user_id: 'u6',
    username: 'l_tanaka',
    full_name: 'L. Tanaka',
    avatar_url: '/avatars/tanaka.jpg',
    bio: 'Behavioral economist. Predicting collective behavior since 2005.',
    location: 'Tokyo, Japan',
    is_premium: true,
    plan: 'creator',
    created_at: '2024-02-20T10:00:00Z',
    updated_at: '2024-03-01T10:00:00Z',
  },
  {
    id: '7',
    user_id: 'u7',
    username: 'r_rodriguez',
    full_name: 'R. Rodriguez',
    avatar_url: '/avatars/rodriguez.jpg',
    bio: 'Political scientist & geopolitics analyst. LatAm & global trends.',
    location: 'Mexico City, Mexico',
    is_premium: false,
    plan: 'free',
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-03-15T10:00:00Z',
  },
  {
    id: '8',
    user_id: 'u8',
    username: 'c_dubois',
    full_name: 'C. Dubois',
    avatar_url: '/avatars/dubois.jpg',
    bio: 'Paris School of Economics. Specialist in European markets & society.',
    location: 'Paris, France',
    is_premium: true,
    plan: 'premium',
    created_at: '2024-03-05T10:00:00Z',
    updated_at: '2024-03-15T10:00:00Z',
  },
  {
    id: '9',
    user_id: 'u9',
    username: 'w_runningbear',
    full_name: 'W. Running Bear',
    avatar_url: '/avatars/runningbear.jpg',
    bio: 'Environmental analyst & sustainability signals curator.',
    location: 'Vancouver, Canada',
    is_premium: false,
    plan: 'free',
    created_at: '2024-03-10T10:00:00Z',
    updated_at: '2024-03-15T10:00:00Z',
  },
  {
    id: '10',
    user_id: 'u10',
    username: 't_nguyen',
    full_name: 'T. Nguyen',
    avatar_url: '/avatars/nguyen.jpg',
    bio: 'Software engineer & AI researcher. Building the intelligence layer.',
    location: 'Ho Chi Minh City, Vietnam',
    is_premium: true,
    plan: 'creator',
    created_at: '2024-03-12T10:00:00Z',
    updated_at: '2024-03-15T10:00:00Z',
  },
  {
    id: '11',
    user_id: 'u11',
    username: 'e_diallo',
    full_name: 'E. Diallo',
    avatar_url: '/avatars/diallo.jpg',
    bio: 'Veteran journalist. Pan-African signals & geopolitics.',
    location: 'Dakar, Senegal',
    is_premium: false,
    plan: 'free',
    created_at: '2024-03-14T10:00:00Z',
    updated_at: '2024-03-15T10:00:00Z',
  },
  {
    id: '12',
    user_id: 'u12',
    username: 'k_oconnell',
    full_name: "K. O'Connell",
    avatar_url: '/avatars/oconnell.jpg',
    bio: 'UX researcher & trend forecaster. Lifestyle & culture signals.',
    location: 'Dublin, Ireland',
    is_premium: false,
    plan: 'premium',
    created_at: '2024-03-15T10:00:00Z',
    updated_at: '2024-03-15T10:00:00Z',
  },
]

export const mockPredictions: Prediction[] = [
  {
    id: 'p1',
    title: 'Will AI surpass human performance on all standard benchmarks by end of 2025?',
    description:
      'Considering recent advances in large language models and multimodal AI, will we see AI systems consistently outperforming humans across all major cognitive benchmarks?',
    category: 'technology',
    type: 'yes_no',
    status: 'open',
    created_by: 'u2',
    creator: mockProfiles[1],
    resolution_date: '2025-12-31T00:00:00Z',
    vote_count: 4821,
    comment_count: 247,
    view_count: 28903,
    featured: true,
    tags: ['AI', 'machine learning', 'benchmarks'],
    options: [
      { id: 'o1', prediction_id: 'p1', label: 'Yes', vote_count: 1736, percentage: 36, is_correct: undefined },
      { id: 'o2', prediction_id: 'p1', label: 'No', vote_count: 3085, percentage: 64, is_correct: undefined },
    ],
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-03-15T10:00:00Z',
  },
  {
    id: 'p2',
    title: 'What will be the Fed Funds Rate at end of Q4 2025?',
    description:
      "Given current inflation trends and the Federal Reserve's stated objectives, predict where the benchmark interest rate will stand at the close of Q4 2025.",
    category: 'finance',
    type: 'multiple_choice',
    status: 'open',
    created_by: 'u8',
    creator: mockProfiles[7],
    resolution_date: '2025-12-31T00:00:00Z',
    vote_count: 3241,
    comment_count: 189,
    view_count: 19204,
    featured: true,
    tags: ['Federal Reserve', 'interest rates', 'macro'],
    options: [
      { id: 'o3', prediction_id: 'p2', label: 'Below 3.5%', vote_count: 421, percentage: 13 },
      { id: 'o4', prediction_id: 'p2', label: '3.5% – 4.0%', vote_count: 1296, percentage: 40 },
      { id: 'o5', prediction_id: 'p2', label: '4.0% – 4.5%', vote_count: 1101, percentage: 34 },
      { id: 'o6', prediction_id: 'p2', label: 'Above 4.5%', vote_count: 423, percentage: 13 },
    ],
    created_at: '2024-03-05T10:00:00Z',
    updated_at: '2024-03-15T10:00:00Z',
  },
  {
    id: 'p3',
    title: 'Probability that Apple releases an AR headset under $1,500 in 2025',
    description:
      'Following the Vision Pro launch at $3,499, Apple has signaled interest in a more accessible spatial computing device.',
    category: 'technology',
    type: 'probability',
    status: 'open',
    created_by: 'u1',
    creator: mockProfiles[0],
    resolution_date: '2025-12-31T00:00:00Z',
    vote_count: 2847,
    comment_count: 156,
    view_count: 16782,
    featured: false,
    tags: ['Apple', 'AR', 'consumer tech'],
    options: [
      { id: 'o7', prediction_id: 'p3', label: 'Community average', vote_count: 2847, percentage: 42 },
    ],
    created_at: '2024-03-08T10:00:00Z',
    updated_at: '2024-03-15T10:00:00Z',
  },
  {
    id: 'p4',
    title: 'Will SpaceX successfully complete a crewed Mars mission by 2030?',
    description:
      'Elon Musk has repeatedly stated 2026-2030 as a target window for the first crewed Mars mission.',
    category: 'science',
    type: 'yes_no',
    status: 'open',
    created_by: 'u10',
    creator: mockProfiles[9],
    resolution_date: '2030-12-31T00:00:00Z',
    vote_count: 5634,
    comment_count: 412,
    view_count: 34201,
    featured: true,
    tags: ['SpaceX', 'Mars', 'space exploration'],
    options: [
      { id: 'o8', prediction_id: 'p4', label: 'Yes', vote_count: 1408, percentage: 25 },
      { id: 'o9', prediction_id: 'p4', label: 'No', vote_count: 4226, percentage: 75 },
    ],
    created_at: '2024-02-20T10:00:00Z',
    updated_at: '2024-03-15T10:00:00Z',
  },
  {
    id: 'p5',
    title: 'Which party will win the next UK general election?',
    description:
      'With the Labour party maintaining a significant poll lead, who do you think will form the next UK government?',
    category: 'politics',
    type: 'multiple_choice',
    status: 'resolved',
    created_by: 'u3',
    creator: mockProfiles[2],
    resolution_date: '2024-07-04T00:00:00Z',
    resolved_at: '2024-07-05T08:00:00Z',
    resolution_notes: 'Labour won with a 172-seat majority.',
    vote_count: 8932,
    comment_count: 634,
    view_count: 67123,
    featured: false,
    tags: ['UK politics', 'elections'],
    options: [
      { id: 'o10', prediction_id: 'p5', label: 'Labour', vote_count: 6699, percentage: 75, is_correct: true },
      { id: 'o11', prediction_id: 'p5', label: 'Conservative', vote_count: 1786, percentage: 20, is_correct: false },
      { id: 'o12', prediction_id: 'p5', label: 'Other / Hung Parliament', vote_count: 447, percentage: 5, is_correct: false },
    ],
    created_at: '2024-01-10T10:00:00Z',
    updated_at: '2024-07-05T10:00:00Z',
  },
  {
    id: 'p6',
    title: 'Will Bitcoin exceed $150,000 before end of 2025?',
    description:
      'After the 2024 halving event and ETF approvals, many analysts are bullish on BTC.',
    category: 'finance',
    type: 'yes_no',
    status: 'open',
    created_by: 'u4',
    creator: mockProfiles[3],
    resolution_date: '2025-12-31T00:00:00Z',
    vote_count: 9234,
    comment_count: 892,
    view_count: 87432,
    featured: true,
    tags: ['Bitcoin', 'crypto', 'price prediction'],
    options: [
      { id: 'o13', prediction_id: 'p6', label: 'Yes', vote_count: 5727, percentage: 62 },
      { id: 'o14', prediction_id: 'p6', label: 'No', vote_count: 3507, percentage: 38 },
    ],
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-03-15T10:00:00Z',
  },
]

// Extended leaderboard with personas matching design boards
const leaderboardPersonas = [
  { full_name: 'C. Laurent', username: 'c_laurent', avatar_url: '/avatars/laurent.jpg', location: 'Paris, France' },
  { full_name: 'L. Faye', username: 'l_faye', avatar_url: '/avatars/faye.jpg', location: 'Dakar, Sénégal' },
  { full_name: 'T. Diop', username: 't_diop', avatar_url: '/avatars/diop.jpg', location: 'Abidjan, CI' },
  { full_name: 'R. Moreau', username: 'r_moreau', avatar_url: '/avatars/moreau.jpg', location: 'Lyon, France' },
  { full_name: 'S. Diallo', username: 's_diallo', avatar_url: '/avatars/diallo2.jpg', location: 'Conakry, Guinée' },
  { full_name: 'Peli & James', username: 'peli_james', avatar_url: '/avatars/peli.jpg', location: 'Kinshasa, RDC' },
  { full_name: 'Guely', username: 'guely', avatar_url: '/avatars/guely.jpg', location: 'Bruxelles, Belgique' },
  { full_name: 'A. Adebayo', username: 'adebayo_a', avatar_url: '/avatars/adebayo.jpg', location: 'Lagos, Nigeria' },
]

export const mockLeaderboard: LeaderboardEntry[] = [
  { rank: 1, user: { ...mockProfiles[0], ...leaderboardPersonas[0], id: 'lb1', user_id: 'lb1', is_premium: true, plan: 'business', created_at: '', updated_at: '' }, score: 9360, accuracy_rate: 76, prediction_count: 170 },
  { rank: 2, user: { ...mockProfiles[1], ...leaderboardPersonas[1], id: 'lb2', user_id: 'lb2', is_premium: true, plan: 'creator', created_at: '', updated_at: '' }, score: 9180, accuracy_rate: 74, prediction_count: 156 },
  { rank: 3, user: { ...mockProfiles[2], ...leaderboardPersonas[2], id: 'lb3', user_id: 'lb3', is_premium: true, plan: 'business', created_at: '', updated_at: '' }, score: 8040, accuracy_rate: 71, prediction_count: 143 },
  { rank: 4, user: { ...mockProfiles[3], ...leaderboardPersonas[3], id: 'lb4', user_id: 'lb4', is_premium: false, plan: 'premium', created_at: '', updated_at: '' }, score: 3090, accuracy_rate: 65, prediction_count: 98 },
  { rank: 5, user: { ...mockProfiles[4], ...leaderboardPersonas[4], id: 'lb5', user_id: 'lb5', is_premium: false, plan: 'free', created_at: '', updated_at: '' }, score: 4270, accuracy_rate: 62, prediction_count: 87 },
  { rank: 6, user: { ...mockProfiles[5], ...leaderboardPersonas[5], id: 'lb6', user_id: 'lb6', is_premium: true, plan: 'creator', created_at: '', updated_at: '' }, score: 69606, accuracy_rate: 78, prediction_count: 430 },
  { rank: 7, user: { ...mockProfiles[6], ...leaderboardPersonas[6], id: 'lb7', user_id: 'lb7', is_premium: true, plan: 'creator', created_at: '', updated_at: '' }, score: 13525, accuracy_rate: 69, prediction_count: 210 },
  { rank: 8, user: { ...mockProfiles[7], ...leaderboardPersonas[7], id: 'lb8', user_id: 'lb8', is_premium: true, plan: 'business', created_at: '', updated_at: '' }, score: 9847, accuracy_rate: 73, prediction_count: 124 },
]

export const mockTrends: InsightTrend[] = [
  { date: '2024-09', predictions: 124, votes: 8432, new_users: 1234 },
  { date: '2024-10', predictions: 189, votes: 12341, new_users: 2156 },
  { date: '2024-11', predictions: 234, votes: 18932, new_users: 3421 },
  { date: '2024-12', predictions: 312, votes: 24123, new_users: 4892 },
  { date: '2025-01', predictions: 421, votes: 34521, new_users: 6234 },
  { date: '2025-02', predictions: 534, votes: 45123, new_users: 8012 },
  { date: '2025-03', predictions: 678, votes: 58912, new_users: 10234 },
]

export const mockCategoryInsights: CategoryInsight[] = [
  { category: 'technology', label: 'Technology', prediction_count: 312, vote_count: 124831, avg_accuracy: 68, trending: true },
  { category: 'finance', label: 'Finance', prediction_count: 234, vote_count: 98234, avg_accuracy: 61, trending: true },
  { category: 'politics', label: 'Politics', prediction_count: 198, vote_count: 87123, avg_accuracy: 55, trending: false },
  { category: 'science', label: 'Science', prediction_count: 156, vote_count: 67421, avg_accuracy: 72, trending: true },
  { category: 'sports', label: 'Sports', prediction_count: 145, vote_count: 56234, avg_accuracy: 64, trending: false },
  { category: 'business', label: 'Business', prediction_count: 123, vote_count: 45123, avg_accuracy: 59, trending: false },
  { category: 'culture', label: 'Culture', prediction_count: 98, vote_count: 34521, avg_accuracy: 57, trending: false },
  { category: 'world', label: 'World', prediction_count: 87, vote_count: 28912, avg_accuracy: 53, trending: false },
]

export const PLATFORM_STATS = {
  total_users: 47832,
  total_predictions: 1353,
  total_votes: 542379,
  avg_accuracy: 64,
  resolved_predictions: 287,
}
